sonar.projectKey=naqlaai
sonar.organization=naqlaai
sonar.host.url=https://sonarcloud.io
sonar.sources=backend/src/main/java,frontend
sonar.exclusions=**/node_modules/**,**/.next/**,**/target/**,**/dist/**
